### ISSUE TITLE
Timeline on offline support?

### ISSUE THREAD

**Issue by romans127** [pi0/nuxt-starter-pwa#1]
Greetings, 

First and foremost nice work on this project. 
I just wanted to know if you have a timeline or thoughts on offline support ?

**Comment by pi0** [comment]
Hi rwatts3, Actually offline support is coming soon. Here is a approx road map:

- Nuxt.js Modules system that is currently is under development
- With next Nuxt.js release there may be some breaking changes as of vue 2.3.x
- We have to implement and benchmark some offline solutions:
  - [offline-plugin](https://github.com/NekR/offline-plugin) 
  - [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin)

**Comment by stephan281094** [comment]
This issue was recently fixed in the Vue Hackernews 2.0 repository. You might consider using the same solution: https://github.com/vuejs/vue-hackernews-2.0/pull/175.

**Comment by pi0** [comment]
Yep. Currently nuxt project has built-in support for offline-plugin. Maybe should consider using sw-precache instead or better than it providing both modules to be used.

**Comment by pi0** [comment]
New official PWA template: https://github.com/nuxt-community/pwa-template
Also we have a new official offline module: https://github.com/nuxt-community/modules/tree/master/modules/workbox

BTW Thanks for all your helps making that happen!
