### ISSUE TITLE
Build to Now fails

### ISSUE THREAD

**Issue by t0ker** [pi0/nuxt-starter-pwa#2]
Got this error when trying to deploy to Now:
` fs.js:1081
>   return binding.unlink(pathModule._makeLong(path));
>                  ^
> Error: EACCES: permission denied, unlink '/home/nowuser/src/.nuxt-helpers/offline.js'`

Any idea what it might be?

**Comment by pi0** [comment]
@t0ker Are u using latest template? (nuxt-helpers should now be replaced with nuxt-modules) so please try crating a fresh instance :)

**Comment by pi0** [comment]
New official PWA template: https://github.com/nuxt-community/pwa-template
